### PR TITLE
Create issue_template.md

### LINKED ISSUE #4: Issue templates
We should also make use of GH issue templates ala microsoft/pxt-microbit repo to aid users in giving meaningful feedback. Not urgent, but I am happy to do this asuming we are making the repo public @jaustin @gary-atkinson

### PR DESCRIPTION
**Pull request by microbit-mark**
first pass at issue template

closes #4

### CODE REVIEW

**Comment by gary-atkinson** [comment]
Can you change the wording of ‘.gif’ to ‘screen recording’ as iOS users should understand that. (The screen recordings are certainly not GIFs anyway).

Unless anyone else chips-in I’m going to put the book version in the Getting Started cutscene at the start of the book if you want to explain where the users can find it. I need to upload a new version for this.

**Comment by microbit-mark** [comment]
Made the changes. GH issues only supports vids in .gif format, so other formats would need to be zipped to be uploaded, which I've noted.

**Comment by microbit-mark** [comment]
Happy to merge? @gary-atkinson @jaustin

**Comment by gary-atkinson** [comment]
Yes, all good with me.

**Pull request merged**
